### ISSUE TITLE
storing data else where?

### ISSUE THREAD

**Issue by EzekielEnns** [winter-again/annotate.nvim#1]
it would be awesome if I could set where the data is stored via a setup flag or something like that?

**Comment by EzekielEnns** [comment]
Think I might try and add this my self will pr if I beat you to it, 
love the plugin, by the way!

**Comment by winter-again** [comment]
> Think I might try and add this my self will pr if I beat you to it, love the plugin, by the way!

Thanks for your kind words, and I'm glad someone has found it useful. To be honest, I've been thinking of archiving the repo since I haven't used it as much as I thought I would and I don't currently have the time to give it the proper attention (i.e., for improvements, maintenance).

I'm more than happy to consider a PR (I haven't looked at the code in a while, but I think it's just a matter of having an additional option in the setup function that you use to set the db location in `db.lua` [here](https://github.com/winter-again/annotate.nvim/blob/0ee7d39626a0c10effa8d945363ee4197b7a0464/lua/annotate/db.lua#L4C1-L5C1), though it may take me some time to go through. If you've really found the plugin integral to your workflow and are interested in maintaining a fork, then I can even point to that one in the README here if I do archive this.

**Comment by winter-again** [comment]
I got curious and fixed some bugs in the main branch but also tried to implement this in the customize-db-location branch. Let me know if this works for you. Also happy to take your PR over this if you get to it and it's cleaner. Mine is just thrown together and seems to work from my cursory testing.

**Comment by EzekielEnns** [comment]
you the man thank you! I'll try it out this week and let you know how it goes

**Comment by EzekielEnns** [comment]
K just tested it out, when deleting I got the error
```
Error executing vim.schedule lua callback: ...mPackages/start/vimplugin-annotate/lua/annotate/init.lua:278: attempt to index local 'extmark' (a number value
)                                                                                                                                                                                                                    
stack traceback:                                                                                                                                                                                                     
        ...mPackages/start/vimplugin-annotate/lua/annotate/init.lua:278: in function <...mPackages/start/vimplugin-annotate/lua/annotate/init.lua:269>
```
So something somewhere in [here](https://github.com/winter-again/annotate.nvim/blob/979dc97efb287a6620179915237f81bf4c7747df/lua/annotate/init.lua#L269-L291)?
I will also mention that this fails to delete the annotation, probably cause of the function just isn't getting past that part, sorry just trying to do this before work 

This is what I set the db_uri to
`db_uri = vim.fn.getcwd() .. '/.annotations_db',`
and the URI seems to be working great, if I delete the db the annotations go away (which is good!)

oh and this is how I'm calling the plugin:
```lua
    ["a"] = { "<cmd>lua require('annotate').delete_annotation()<cr>", "delete annoation" },
    ["A"] = { "<cmd>lua require('annotate').create_annotation()<cr>", "add annotation" },
```
It's just via which-key

**Comment by winter-again** [comment]
I'm not able to reproduce the error on deleting an annotation. I'll keep this issue open in case you have more details. Otherwise, I'll probably merge this branch into main soon and then consider archiving again. Feel free to let me know if you'd like to maintain a fork. Like I said, I'm happy to link to that fork in the readme here in case people come looking. Thanks.

**Comment by EzekielEnns** [comment]
It works :smile: just had to pull again ty for the plugin it's super helpful
